In [1]:
import sys
sys.path.append("..")
from src.loading import load_csv_data

In [2]:
df_raw = load_csv_data("/Users/laumagoldmann/Desktop/SDS210_IndividualProject/data/raw/stzh.zwn_meldungen_p.csv")

In [3]:
from src.cleaning import parse_datetime_columns, remove_duplicate_reports

# using the functions from the cleaning.py script for changing the time and to check for duplicates
df_test = parse_datetime_columns(df_raw)
df_test = remove_duplicate_reports(df_test)

# output shows if there is a difference to the raw dataset and the cleaned dataset
print(df_raw.shape)
print(df_test.shape)

(72567, 19)
(72567, 19)

In [4]:
import src.cleaning

from src.cleaning import (
    parse_datetime_columns,
    remove_duplicate_reports,
    add_time_columns
)

df_test = parse_datetime_columns(df_raw)
df_test = remove_duplicate_reports(df_test)
df_test = add_time_columns(df_test)

df_test[["requested_datetime", "year", "month", "year_month"]].head()

   requested_datetime  year  month year_month
0 2013-03-14 15:16:15  2013      3 2013-03-01
1 2013-03-14 15:17:57  2013      3 2013-03-01
2 2013-03-15 09:14:16  2013      3 2013-03-01
3 2013-03-15 09:17:15  2013      3 2013-03-01
4 2013-03-15 10:36:53  2013      3 2013-03-01

In [5]:
import importlib
import src.cleaning

importlib.reload(src.cleaning)

from src.cleaning import clean_reports

df_clean = clean_reports(df_raw)

df_clean[["requested_datetime", "year", "month", "year_month"]].head()

   requested_datetime  year  month year_month
0 2013-03-14 15:16:15  2013      3 2013-03-01
1 2013-03-14 15:17:57  2013      3 2013-03-01
2 2013-03-15 09:14:16  2013      3 2013-03-01
3 2013-03-15 09:17:15  2013      3 2013-03-01
4 2013-03-15 10:36:53  2013      3 2013-03-01

In [7]:
df_clean.to_csv("../data/processed/zueriwieneu_cleaned.csv", index=False)